### ISSUE TITLE
Toggle Subtask Done Status

### ISSUE THREAD

**Issue by joshelvn11** [joshelvn11/ish-app#28]
**Description**: Implement functionality to toggle the done status of subtasks within an item.

**User Story**: As a user, I want to be able to mark subtasks as done or not done so that I can easily track the progress of my tasks.

**Acceptance Criteria**:

- [x] Each subtask item includes a checkbox.
- [x] The checked/unchecked state of the checkbox corresponds to the `done` property in the subtask JSON object.
- [x] When a subtask item is marked as done, the text in the text field is displayed with a strikethrough and greyed out.
- [x] Clicking the checkbox toggles the `done` property in the subtask JSON object and sends a PATCH request to the server with the updated JSON object.
- [x] The text of the subtask item updates to reflect the done status (original for not done, strikethrough and greyed out for done) when the checkbox is clicked.
- [x] Upon successful update:
  - [x] A success notification is displayed to the user.
- [x] If the update fails:
  - [x] An error notification is shown to the user.
